In [1]:
from libs.model import MMSA, MMSAConfig
from torch import Tensor


config = MMSAConfig(feature_extractor="jinaai/jina-clip-v1")
model = MMSA(config).cuda()

/home/davide/mambaforge/envs/MSA/lib/python3.11/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


In [2]:
from libs.dataset_loader import MulTweEmoDataset
dataset = MulTweEmoDataset.load()["train"]


Generating train split: 0 examples [00:00, ? examples/s]

In [3]:
n_samples = 10
start = 10

dataset = dataset[start:start+n_samples]

sentences=dataset["tweet"]
image_urls=dataset["img_path"]
labels=dataset["labels"]

In [4]:
# from transformers import PreTrainedModel, AutoModel, AutoProcessor
# processor = AutoProcessor.from_pretrained("openai/clip-vit-large-patch14", trust_remote_code=True)
# feature_extractor = AutoModel.from_pretrained("openai/clip-vit-large-patch14", trust_remote_code=True)

In [5]:
model(sentences, image_urls)

tensor([[0.5976, 0.4610, 0.5776, 0.5446, 0.5058, 0.5917, 0.4623, 0.4573, 0.4499,
         0.5057],
        [0.4903, 0.4792, 0.6104, 0.5113, 0.4635, 0.6359, 0.5314, 0.5373, 0.5384,
         0.4841],
        [0.5517, 0.5914, 0.6459, 0.5748, 0.4715, 0.5284, 0.5255, 0.5219, 0.6013,
         0.3922],
        [0.4563, 0.6328, 0.7271, 0.6181, 0.4942, 0.5818, 0.5202, 0.4271, 0.4848,
         0.4322],
        [0.4817, 0.4770, 0.5454, 0.5066, 0.4971, 0.5546, 0.5231, 0.4302, 0.4712,
         0.6133],
        [0.6370, 0.5468, 0.5209, 0.4476, 0.3688, 0.7733, 0.4598, 0.5659, 0.4914,
         0.5579],
        [0.6276, 0.4560, 0.5243, 0.4399, 0.5097, 0.5046, 0.5804, 0.4752, 0.4736,
         0.4847],
        [0.5378, 0.4772, 0.5642, 0.5056, 0.4490, 0.5445, 0.4025, 0.5081, 0.5386,
         0.5537],
        [0.5750, 0.4550, 0.5681, 0.5565, 0.4421, 0.5910, 0.4963, 0.4334, 0.4934,
         0.4657],
        [0.5316, 0.5585, 0.6237, 0.5876, 0.4373, 0.5724, 0.5543, 0.4952, 0.5340,
         0.4415]], device='c

In [6]:
labels = Tensor(labels).cuda()
model.eval()
model(sentences, image_urls, labels)

{'loss': tensor(0.7492, device='cuda:0', grad_fn=<BinaryCrossEntropyBackward0>),
 'logits': tensor([[0.5976, 0.4610, 0.5776, 0.5446, 0.5058, 0.5917, 0.4623, 0.4573, 0.4499,
          0.5057],
         [0.4903, 0.4792, 0.6104, 0.5113, 0.4635, 0.6359, 0.5314, 0.5373, 0.5384,
          0.4841],
         [0.5517, 0.5914, 0.6459, 0.5748, 0.4715, 0.5284, 0.5255, 0.5219, 0.6013,
          0.3922],
         [0.4563, 0.6328, 0.7271, 0.6181, 0.4942, 0.5818, 0.5202, 0.4271, 0.4848,
          0.4322],
         [0.4817, 0.4770, 0.5454, 0.5066, 0.4971, 0.5546, 0.5231, 0.4302, 0.4712,
          0.6133],
         [0.6370, 0.5468, 0.5209, 0.4476, 0.3688, 0.7733, 0.4598, 0.5659, 0.4914,
          0.5579],
         [0.6276, 0.4560, 0.5243, 0.4399, 0.5097, 0.5046, 0.5804, 0.4752, 0.4736,
          0.4847],
         [0.5378, 0.4772, 0.5642, 0.5056, 0.4490, 0.5445, 0.4025, 0.5081, 0.5386,
          0.5537],
         [0.5750, 0.4550, 0.5681, 0.5565, 0.4421, 0.5910, 0.4963, 0.4334, 0.4934,
          0.4657],


In [7]:
labels

tensor([[0., 0., 0., 0., 1., 0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 1., 1., 0.],
        [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 1., 0., 1.]], device='cuda:0')

In [8]:
next(model.parameters()).is_cuda

True

In [9]:
import torch
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [10]:
# lul1 = model.feature_extractor.vision_model.blocks[8].norm2.weight.clone()

In [11]:
for i in range(0, 10):
    optimizer.zero_grad()
    model.train()
    outputs = model(sentences, image_urls, labels)
    outputs["loss"].backward()
    # Compute the loss and its gradients
    # loss = torch.nn.functional.binary_cross_entropy(outputs, labels.unsqueeze(-1))
    # loss.backward()

    # Adjust learning weights
    optimizer.step()
    

RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


In [ ]:
for name, param in model.named_parameters():
    if param.grad is None:
        print(name)
    # print(param.grad, name)

feature_extractor.logit_scale


In [ ]:
# lul = model.feature_extractor.vision_model.blocks[8].norm2.weight.clone()

In [ ]:
# lol = 0
# for i, j in zip(lul1, lul):
#     if i != j:
#         lol+= 1
# print(lol, lul.shape)

In [ ]:
torch.set_printoptions(precision=10)

In [ ]:
model(sentences, image_urls, labels)

{'loss': tensor(0.0304777436, device='cuda:0', grad_fn=<BinaryCrossEntropyBackward0>),
 'logits': tensor([[1.1323823128e-03, 1.7100878060e-01, 9.8436092958e-04, 5.9577065986e-04,
          9.7188073397e-01, 1.2738171790e-04, 5.3404801292e-04, 1.9860996399e-03,
          1.1114297807e-01, 9.0812641382e-01],
         [1.0988342110e-03, 9.6902769804e-01, 1.0930653661e-03, 4.1077233618e-04,
          6.6075816751e-02, 1.0772660607e-03, 5.2523106569e-04, 1.2497873977e-03,
          2.4091595784e-02, 6.0802042484e-02],
         [6.8346019834e-03, 9.3929207325e-01, 1.9114090828e-03, 7.0984475315e-03,
          5.8356001973e-02, 1.3232221827e-03, 1.4694945887e-02, 2.1165024489e-02,
          9.9915659428e-01, 1.0353769362e-01]], device='cuda:0',
        grad_fn=<SigmoidBackward0>)}

In [ ]:
labels

tensor([[0., 0., 0., 0., 1., 0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 1., 0.]], device='cuda:0')